version: "3.7"
services:
  container-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${UVICORN_PORT}:${UVICORN_PORT}
    #Directly attach working dir to container
    #volumes:
    #  - ./app:/code/
    
    restart: unless-stopped
    env_file: .env
    
    # environment variables from .env file
    #environment:
      #USER_NAME: ${USER_NAME}
      #USER_PASSWORD: ${USER_PASSWORD}
