name: Pytest and Pylints

on: [push]

env:
  USER_NAME: testuser
  USER_PASSWORD: testpassword

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pylint
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          pytest
      - name: Analysing the code with pylint
        run: |
          pylint --disable=import-error,unused-argument --ignore=test_app.py $(git ls-files '*.py')
